/* Formações táticas.
   Cada slot: { cat, x, y, label }
   x: 0 (esquerda) a 100 (direita)
   y: 0 (ataque, gol adversário no topo) a 100 (defesa, nosso gol embaixo) */
const FORMATIONS = {
  "3-4-3": [
    { cat: "GK",  x: 50, y: 91, label: "GOL" },
    { cat: "DEF", x: 24, y: 71, label: "ZAG" },
    { cat: "DEF", x: 50, y: 74, label: "ZAG" },
    { cat: "DEF", x: 76, y: 71, label: "ZAG" },
    { cat: "MID", x: 14, y: 48, label: "ALA" },
    { cat: "MID", x: 38, y: 50, label: "MEI" },
    { cat: "MID", x: 62, y: 50, label: "MEI" },
    { cat: "MID", x: 86, y: 48, label: "ALA" },
    { cat: "FWD", x: 25, y: 22, label: "PON" },
    { cat: "FWD", x: 50, y: 17, label: "ATA" },
    { cat: "FWD", x: 75, y: 22, label: "PON" },
  ],
  "4-3-3": [
    { cat: "GK",  x: 50, y: 91, label: "GOL" },
    { cat: "DEF", x: 16, y: 71, label: "LAT" },
    { cat: "DEF", x: 39, y: 75, label: "ZAG" },
    { cat: "DEF", x: 61, y: 75, label: "ZAG" },
    { cat: "DEF", x: 84, y: 71, label: "LAT" },
    { cat: "MID", x: 28, y: 50, label: "MEI" },
    { cat: "MID", x: 50, y: 53, label: "VOL" },
    { cat: "MID", x: 72, y: 50, label: "MEI" },
    { cat: "FWD", x: 25, y: 22, label: "PON" },
    { cat: "FWD", x: 50, y: 17, label: "ATA" },
    { cat: "FWD", x: 75, y: 22, label: "PON" },
  ],
  "4-4-2": [
    { cat: "GK",  x: 50, y: 91, label: "GOL" },
    { cat: "DEF", x: 16, y: 71, label: "LAT" },
    { cat: "DEF", x: 39, y: 75, label: "ZAG" },
    { cat: "DEF", x: 61, y: 75, label: "ZAG" },
    { cat: "DEF", x: 84, y: 71, label: "LAT" },
    { cat: "MID", x: 15, y: 48, label: "ALA" },
    { cat: "MID", x: 38, y: 51, label: "VOL" },
    { cat: "MID", x: 62, y: 51, label: "MEI" },
    { cat: "MID", x: 85, y: 48, label: "ALA" },
    { cat: "FWD", x: 38, y: 20, label: "ATA" },
    { cat: "FWD", x: 62, y: 20, label: "ATA" },
  ],
  "3-5-2": [
    { cat: "GK",  x: 50, y: 91, label: "GOL" },
    { cat: "DEF", x: 25, y: 72, label: "ZAG" },
    { cat: "DEF", x: 50, y: 75, label: "ZAG" },
    { cat: "DEF", x: 75, y: 72, label: "ZAG" },
    { cat: "MID", x: 12, y: 52, label: "ALA" },
    { cat: "MID", x: 33, y: 50, label: "VOL" },
    { cat: "MID", x: 50, y: 55, label: "MEI" },
    { cat: "MID", x: 67, y: 50, label: "VOL" },
    { cat: "MID", x: 88, y: 52, label: "ALA" },
    { cat: "FWD", x: 38, y: 22, label: "ATA" },
    { cat: "FWD", x: 62, y: 22, label: "ATA" },
  ],
  "4-2-3-1": [
    { cat: "GK",  x: 50, y: 91, label: "GOL" },
    { cat: "DEF", x: 16, y: 72, label: "LAT" },
    { cat: "DEF", x: 39, y: 76, label: "ZAG" },
    { cat: "DEF", x: 61, y: 76, label: "ZAG" },
    { cat: "DEF", x: 84, y: 72, label: "LAT" },
    { cat: "MID", x: 36, y: 58, label: "VOL" },
    { cat: "MID", x: 64, y: 58, label: "VOL" },
    { cat: "MID", x: 22, y: 37, label: "MEI" },
    { cat: "MID", x: 50, y: 40, label: "MEI" },
    { cat: "MID", x: 78, y: 37, label: "MEI" },
    { cat: "FWD", x: 50, y: 17, label: "ATA" },
  ],
  "5-3-2": [
    { cat: "GK",  x: 50, y: 91, label: "GOL" },
    { cat: "DEF", x: 12, y: 69, label: "ALA" },
    { cat: "DEF", x: 31, y: 74, label: "ZAG" },
    { cat: "DEF", x: 50, y: 77, label: "ZAG" },
    { cat: "DEF", x: 69, y: 74, label: "ZAG" },
    { cat: "DEF", x: 88, y: 69, label: "ALA" },
    { cat: "MID", x: 28, y: 48, label: "MEI" },
    { cat: "MID", x: 50, y: 51, label: "VOL" },
    { cat: "MID", x: 72, y: 48, label: "MEI" },
    { cat: "FWD", x: 38, y: 22, label: "ATA" },
    { cat: "FWD", x: 62, y: 22, label: "ATA" },
  ],
};

const CAT_NAMES = { GK: "Goleiro", DEF: "Defensor", MID: "Meio-campo", FWD: "Atacante" };
