/* Base de jogadores lendários.
   cat: GK (goleiro), DEF (defensores), MID (meio-campo), FWD (ataque)
   ovr: overall (0-99) usado no modo clássico e no cálculo do resultado. */
const PLAYERS = [
  // ===== Goleiros =====
  { name: "Pelé",            cat: "FWD", ovr: 97, flag: "🇧🇷", era: "1958–70" },
  { name: "Garrincha",       cat: "FWD", ovr: 93, flag: "🇧🇷", era: "1958–62" },
  { name: "Ronaldo Fenômeno",cat: "FWD", ovr: 95, flag: "🇧🇷", era: "1994–06" },
  { name: "Romário",         cat: "FWD", ovr: 92, flag: "🇧🇷", era: "1990–00" },
  { name: "Neymar",          cat: "FWD", ovr: 90, flag: "🇧🇷", era: "2011–" },
  { name: "Bebeto",          cat: "FWD", ovr: 86, flag: "🇧🇷", era: "1990–98" },
  { name: "Tostão",          cat: "FWD", ovr: 87, flag: "🇧🇷", era: "1966–72" },
  { name: "Careca",          cat: "FWD", ovr: 85, flag: "🇧🇷", era: "1986–90" },
  { name: "Ademir",          cat: "FWD", ovr: 85, flag: "🇧🇷", era: "1950" },
  { name: "Vavá",            cat: "FWD", ovr: 84, flag: "🇧🇷", era: "1958–62" },
  { name: "Rivaldo",         cat: "FWD", ovr: 90, flag: "🇧🇷", era: "1998–02" },
  { name: "Lionel Messi",    cat: "FWD", ovr: 96, flag: "🇦🇷", era: "2005–" },
  { name: "Diego Maradona",  cat: "FWD", ovr: 95, flag: "🇦🇷", era: "1979–94" },
  { name: "Cristiano Ronaldo",cat:"FWD", ovr: 95, flag: "🇵🇹", era: "2003–" },
  { name: "Eusébio",         cat: "FWD", ovr: 92, flag: "🇵🇹", era: "1961–73" },
  { name: "Di Stéfano",      cat: "FWD", ovr: 93, flag: "🇦🇷", era: "1947–66" },
  { name: "Johan Cruyff",    cat: "FWD", ovr: 94, flag: "🇳🇱", era: "1966–84" },
  { name: "Van Basten",      cat: "FWD", ovr: 92, flag: "🇳🇱", era: "1983–95" },
  { name: "Gerd Müller",     cat: "FWD", ovr: 91, flag: "🇩🇪", era: "1965–82" },
  { name: "Puskás",          cat: "FWD", ovr: 92, flag: "🇭🇺", era: "1945–66" },
  { name: "Thierry Henry",   cat: "FWD", ovr: 90, flag: "🇫🇷", era: "1994–14" },
  { name: "Luis Suárez",     cat: "FWD", ovr: 88, flag: "🇺🇾", era: "2005–" },

  // ===== Meio-campo =====
  { name: "Ronaldinho Gaúcho",cat:"MID", ovr: 92, flag: "🇧🇷", era: "1999–15" },
  { name: "Zico",            cat: "MID", ovr: 91, flag: "🇧🇷", era: "1971–89" },
  { name: "Kaká",            cat: "MID", ovr: 89, flag: "🇧🇷", era: "2001–17" },
  { name: "Sócrates",        cat: "MID", ovr: 89, flag: "🇧🇷", era: "1974–89" },
  { name: "Didi",            cat: "MID", ovr: 89, flag: "🇧🇷", era: "1952–62" },
  { name: "Gérson",          cat: "MID", ovr: 88, flag: "🇧🇷", era: "1958–73" },
  { name: "Falcão",          cat: "MID", ovr: 88, flag: "🇧🇷", era: "1973–86" },
  { name: "Rivelino",        cat: "MID", ovr: 88, flag: "🇧🇷", era: "1965–81" },
  { name: "Clodoaldo",       cat: "MID", ovr: 84, flag: "🇧🇷", era: "1969–71" },
  { name: "Dunga",           cat: "MID", ovr: 83, flag: "🇧🇷", era: "1987–98" },
  { name: "Gilberto Silva",  cat: "MID", ovr: 83, flag: "🇧🇷", era: "2001–10" },
  { name: "Zidane",          cat: "MID", ovr: 94, flag: "🇫🇷", era: "1991–06" },
  { name: "Platini",         cat: "MID", ovr: 91, flag: "🇫🇷", era: "1972–87" },
  { name: "Iniesta",         cat: "MID", ovr: 91, flag: "🇪🇸", era: "2002–18" },
  { name: "Xavi",            cat: "MID", ovr: 90, flag: "🇪🇸", era: "1998–15" },
  { name: "Luka Modrić",     cat: "MID", ovr: 89, flag: "🇭🇷", era: "2003–" },
  { name: "Steven Gerrard",  cat: "MID", ovr: 88, flag: "🏴", era: "1998–15" },
  { name: "Lothar Matthäus", cat: "MID", ovr: 89, flag: "🇩🇪", era: "1980–00" },

  // ===== Defensores =====
  { name: "Cafu",            cat: "DEF", ovr: 90, flag: "🇧🇷", era: "1990–08" },
  { name: "Roberto Carlos",  cat: "DEF", ovr: 91, flag: "🇧🇷", era: "1992–08" },
  { name: "Carlos Alberto",  cat: "DEF", ovr: 89, flag: "🇧🇷", era: "1964–77" },
  { name: "Nílton Santos",   cat: "DEF", ovr: 88, flag: "🇧🇷", era: "1949–64" },
  { name: "Djalma Santos",   cat: "DEF", ovr: 87, flag: "🇧🇷", era: "1952–68" },
  { name: "Lúcio",           cat: "DEF", ovr: 86, flag: "🇧🇷", era: "2000–11" },
  { name: "Aldair",          cat: "DEF", ovr: 85, flag: "🇧🇷", era: "1989–00" },
  { name: "Thiago Silva",    cat: "DEF", ovr: 88, flag: "🇧🇷", era: "2008–" },
  { name: "Marcelo",         cat: "DEF", ovr: 86, flag: "🇧🇷", era: "2006–" },
  { name: "Maicon",          cat: "DEF", ovr: 85, flag: "🇧🇷", era: "2003–16" },
  { name: "Júnior",          cat: "DEF", ovr: 85, flag: "🇧🇷", era: "1974–93" },
  { name: "Paolo Maldini",   cat: "DEF", ovr: 93, flag: "🇮🇹", era: "1984–09" },
  { name: "Franz Beckenbauer",cat:"DEF", ovr: 93, flag: "🇩🇪", era: "1964–83" },
  { name: "Cannavaro",       cat: "DEF", ovr: 90, flag: "🇮🇹", era: "1992–11" },
  { name: "Franco Baresi",   cat: "DEF", ovr: 90, flag: "🇮🇹", era: "1977–97" },
  { name: "Sergio Ramos",    cat: "DEF", ovr: 89, flag: "🇪🇸", era: "2004–" },
  { name: "Carles Puyol",    cat: "DEF", ovr: 87, flag: "🇪🇸", era: "1999–14" },

  // ===== Goleiros =====
  { name: "Taffarel",        cat: "GK",  ovr: 89, flag: "🇧🇷", era: "1988–98" },
  { name: "Dida",            cat: "GK",  ovr: 86, flag: "🇧🇷", era: "1995–06" },
  { name: "Gilmar",          cat: "GK",  ovr: 85, flag: "🇧🇷", era: "1953–69" },
  { name: "Marcos",          cat: "GK",  ovr: 85, flag: "🇧🇷", era: "1998–02" },
  { name: "Rogério Ceni",    cat: "GK",  ovr: 84, flag: "🇧🇷", era: "1990–15" },
  { name: "Gianluigi Buffon",cat: "GK",  ovr: 92, flag: "🇮🇹", era: "1995–23" },
  { name: "Iker Casillas",   cat: "GK",  ovr: 91, flag: "🇪🇸", era: "1999–19" },
  { name: "Lev Yashin",      cat: "GK",  ovr: 90, flag: "🇷🇺", era: "1950–70" },
  { name: "Manuel Neuer",    cat: "GK",  ovr: 91, flag: "🇩🇪", era: "2006–" },
  { name: "Gordon Banks",    cat: "GK",  ovr: 88, flag: "🏴", era: "1958–72" },
];
